<?php
/*
+--------------------------------------------------------------------+
| CiviCRM version 4.7                                                |
+--------------------------------------------------------------------+
| Copyright CiviCRM LLC (c) 2004-2017                                |
+--------------------------------------------------------------------+
| This file is a part of CiviCRM.                                    |
|                                                                    |
| CiviCRM is free software; you can copy, modify, and distribute it  |
| under the terms of the GNU Affero General Public License           |
| Version 3, 19 November 2007 and the CiviCRM Licensing Exception.   |
|                                                                    |
| CiviCRM is distributed in the hope that it will be useful, but     |
| WITHOUT ANY WARRANTY; without even the implied warranty of         |
| MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.               |
| See the GNU Affero General Public License for more details.        |
|                                                                    |
| You should have received a copy of the GNU Affero General Public   |
| License and the CiviCRM Licensing Exception along                  |
| with this program; if not, contact CiviCRM LLC                     |
| at info[AT]civicrm[DOT]org. If you have questions about the        |
| GNU Affero General Public License or the licensing of CiviCRM,     |
| see the CiviCRM license FAQ at http://civicrm.org/licensing        |
+--------------------------------------------------------------------+
*/
/**
 * @package CRM
 * @copyright CiviCRM LLC (c) 2004-2017
 *
 * Generated from xml/schema/CRM/Team/TeamEntity.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:f1abf5f30d5586816413d582db09715d)
 */
require_once 'CRM/Core/DAO.php';
require_once 'CRM/Utils/Type.php';
/**
 * CRM_Team_DAO_TeamEntity constructor.
 */
class CRM_Team_DAO_TeamEntity extends CRM_Core_DAO {
  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  static $_tableName = 'civicrm_team_entity';
  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var boolean
   */
  static $_log = true;
  /**
   * Unique TeamEntity ID
   *
   * @var int unsigned
   */
  public $id;
  /**
   * FK to civicrm_team
   *
   * @var int unsigned
   */
  public $team_id;
  /**
   * FK to Entity
   *
   * @var int unsigned
   */
  public $entity_id;
  /**
   * Entity name
   *
   * @var string
   */
  public $entity_name;
  /**
   * Date on which the Entity was added to the team
   *
   * @var timestamp
   */
  public $date_added;
  /**
   * Date on which record is updated
   *
   * @var timestamp
   */
  public $date_modified;
  /**
   * Indicates if the entity is currently attached with the Team.
   *
   * @var boolean
   */
  public $isactive;
  /**
   * Class constructor.
   */
  function __construct() {
    $this->__table = 'civicrm_team_entity';
    parent::__construct();
  }
  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static ::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName() , 'team_id', 'civicrm_team', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }
  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = array(
        'id' => array(
          'name' => 'id',
          'title' => ts('Id') ,
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'Unique TeamEntity ID',
          'required' => true,
          'table_name' => 'civicrm_team_entity',
          'entity' => 'TeamEntity',
          'bao' => 'CRM_Team_DAO_TeamEntity',
          'localizable' => 0,
        ) ,
        'team_id' => array(
          'name' => 'team_id',
          'title' => ts('Team Id') ,
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'FK to civicrm_team',
          'required' => true,
          'table_name' => 'civicrm_team_entity',
          'entity' => 'TeamEntity',
          'bao' => 'CRM_Team_DAO_TeamEntity',
          'localizable' => 0,
          'FKClassName' => 'CRM_Team_DAO_Team',
          'pseudoconstant' => array(
            'table' => 'civicrm_team',
            'keyColumn' => 'id',
            'labelColumn' => 'team_name',
          )
        ) ,
        'entity_id' => array(
          'name' => 'entity_id',
          'title' => ts('Entity Id') ,
          'type' => CRM_Utils_Type::T_INT,
          'description' => 'FK to Entity',
          'required' => true,
          'table_name' => 'civicrm_team_entity',
          'entity' => 'TeamEntity',
          'bao' => 'CRM_Team_DAO_TeamEntity',
          'localizable' => 0,
        ) ,
        'entity_name' => array(
          'name' => 'entity_name',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => ts('Entity name') ,
          'description' => 'Entity name',
          'required' => true,
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'table_name' => 'civicrm_team_entity',
          'entity' => 'TeamEntity',
          'bao' => 'CRM_Team_DAO_TeamEntity',
          'localizable' => 0,
        ) ,
        'date_added' => array(
          'name' => 'date_added',
          'type' => CRM_Utils_Type::T_TIMESTAMP,
          'title' => ts('Date Added') ,
          'description' => 'Date on which the Entity was added to the team',
          'required' => false,
          'default' => 'CURRENT_TIMESTAMP',
          'table_name' => 'civicrm_team_entity',
          'entity' => 'TeamEntity',
          'bao' => 'CRM_Team_DAO_TeamEntity',
          'localizable' => 0,
        ) ,
        'date_modified' => array(
          'name' => 'date_modified',
          'type' => CRM_Utils_Type::T_TIMESTAMP,
          'title' => ts('Date Modified') ,
          'description' => 'Date on which record is updated',
          'required' => false,
          'default' => 'CURRENT_TIMESTAMP',
          'table_name' => 'civicrm_team_entity',
          'entity' => 'TeamEntity',
          'bao' => 'CRM_Team_DAO_TeamEntity',
          'localizable' => 0,
        ) ,
        'isactive' => array(
          'name' => 'isactive',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => ts('IsActive') ,
          'description' => 'Indicates if the entity is currently attached with the Team.',
          'required' => true,
          'table_name' => 'civicrm_team_entity',
          'entity' => 'TeamEntity',
          'bao' => 'CRM_Team_DAO_TeamEntity',
          'localizable' => 0,
        ) ,
      );
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }
  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }
  /**
   * Returns the names of this table
   *
   * @return string
   */
  static function getTableName() {
    return self::$_tableName;
  }
  /**
   * Returns if this table needs to be logged
   *
   * @return boolean
   */
  function getLog() {
    return self::$_log;
  }
  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  static function &import($prefix = false) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'team_entity', $prefix, array());
    return $r;
  }
  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  static function &export($prefix = false) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'team_entity', $prefix, array());
    return $r;
  }
  /**
   * Returns the list of indices
   */
  public static function indices($localize = TRUE) {
    $indices = array(
      'UI_team_entity_id' => array(
        'name' => 'UI_team_entity_id',
        'field' => array(
          0 => 'team_id',
          1 => 'entity_id',
          2 => 'entity_name',
        ) ,
        'localizable' => false,
        'unique' => true,
        'sig' => 'civicrm_team_entity::1::team_id::entity_id::entity_name',
      ) ,
    );
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }
}
